name: Matrix Workflow

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - project_dir: glassdoor-scraper
            test: test_salary_scraping
          - project_dir: zoopla-scraper
            test: test_properties_scraping

    steps:
    - uses: actions/checkout@v2

    - name: Record test results
      run: |
        echo "${{ matrix.test }} failed in ${{ matrix.project_dir }}" >> test_failures.txt

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results-${{ matrix.project_dir }}
        path: test_failures.txt

  report:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Download test results
      uses: actions/download-artifact@v2
      with:
        name: test-results-*
        path: ./

    - name: Aggregate test failures
      run: |
        echo "Aggregating test results..."
        cat test-results-*.txt > all_test_failures.txt

    - name: Report test failures
      if: failure()
      run: |
        echo "Test failures found:"
        cat all_test_failures.txt