name: Scraper Tests
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        include:
          - project_dir: glassdoor-scraper
            test: test_salary_scraping
          - project_dir: zoopla-scraper
            test: test_properties_scraping

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Cache Poetry virtual environment
      uses: actions/cache@v2
      id: cache
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/${{ matrix.project_dir }}/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    - name: Install dependencies
      run: |
        cd ${{ matrix.project_dir }}
        poetry install

    - name: Run test
      env:
        SCRAPFLY_KEY: ${{ secrets.SCRAPFLY_KEY }}
      run: |
        cd ${{ matrix.project_dir }}
        poetry run pytest test.py -k ${{ matrix.test }}

    - name: Send Slack notification
      uses: 8398a7/action-slack@v3
      if: failure()
      with:
        status: custom
        fields: workflowRun
        custom_payload: |
          {
            text: "Test failed",
            attachments: [{
              color: "danger",
              text: `${process.env.AS_WORKFLOW_RUN} ${{ matrix.project_dir }}: ${{ matrix.test }}`,
            }]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
