name: Glassdoor.com Test
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * FRI'

env:
  PROJECT_DIR: glassdoor-scraper

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test: [test_find_companies, test_job_scraping, test_salary_scraping, test_review_scraping]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Cache Poetry virtual environment
      uses: actions/cache@v2
      id: cache
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/${{ env.PROJECT_DIR }}/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    - name: Install dependencies
      run: |
        cd ${{ env.PROJECT_DIR }}
        poetry install

    - name: Run test
      env:
        SCRAPFLY_KEY: ${{ secrets.SCRAPFLY_KEY }}
      run: |
        cd ${{ env.PROJECT_DIR }}
        poetry run pytest test.py -k ${{ matrix.test }}

  notify:
    runs-on: ubuntu-latest
    needs: test
    if: failure()  # only report failures
    steps:
    - name: Send Slack notification
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: workflowRun
        custom_payload: |
          {
            attachments: [{
              color: "danger",
              text: `${process.env.AS_WORFKLOW} ${process.env.AS_JOB} failed: ${{ job.status }}`,
            }]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}